services:
  ollama:
    image: ollama/ollama
    container_name: jernkors-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/ollama/storage
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
volumes:
  ollama_data:
